"""
Generated By: Cursor (Claude Sonnet 4.5)

Configuration for calibration master generation.

Defines required FITS keywords for grouping each frame type.
Uses normalized keyword names from ap-common normalization.
"""

# Normalized keyword names (as returned by ap-common)
# These match the normalized output from ap_common.normalize_headers()
KEYWORD_TYPE = "type"  # From IMAGETYP
KEYWORD_CAMERA = "camera"  # From INSTRUME
KEYWORD_SETTEMP = "settemp"  # From SET-TEMP or SETTEMP
KEYWORD_GAIN = "gain"  # From GAIN (lowercase)
KEYWORD_OFFSET = "offset"  # From OFFSET (lowercase)
KEYWORD_READOUTMODE = "readoutmode"  # From READOUTM
KEYWORD_EXPOSURESECONDS = "exposureseconds"  # From EXPOSURE/EXPTIME/EXP
KEYWORD_DATE = "date"  # From DATE-OBS
KEYWORD_FILTER = "filter"  # From FILTER

# Required FITS keywords for grouping each frame type
# Keys are frame types (as found in TYPE keyword)
# Values are lists of normalized keyword names required for grouping
REQUIRED_KEYWORDS = {
    "bias": [
        KEYWORD_TYPE,
        KEYWORD_SETTEMP,
        KEYWORD_GAIN,
        KEYWORD_OFFSET,
        KEYWORD_CAMERA,
        KEYWORD_READOUTMODE,
    ],
    "dark": [
        KEYWORD_TYPE,
        KEYWORD_EXPOSURESECONDS,
        KEYWORD_SETTEMP,
        KEYWORD_GAIN,
        KEYWORD_OFFSET,
        KEYWORD_CAMERA,
        KEYWORD_READOUTMODE,
    ],
    "flat": [
        KEYWORD_TYPE,
        KEYWORD_FILTER,
        KEYWORD_DATE,
        KEYWORD_SETTEMP,
        KEYWORD_GAIN,
        KEYWORD_OFFSET,
        KEYWORD_CAMERA,
        KEYWORD_READOUTMODE,
    ],
}

# Keywords used for matching bias/dark masters to flats
# These are the instrument settings that must match
# (excludes DATE and FILTER, which are flat-specific)
MASTER_MATCH_KEYWORDS = [
    KEYWORD_CAMERA,
    KEYWORD_SETTEMP,
    KEYWORD_GAIN,
    KEYWORD_OFFSET,
    KEYWORD_READOUTMODE,
]

# Frame types to ignore (e.g., lights)
IGNORED_TYPES = ["light"]

# PixInsight ImageIntegration imageType constants
IMAGE_TYPE_BIAS = 1
IMAGE_TYPE_DARK = 2
IMAGE_TYPE_FLAT = 3
